### ISSUE TITLE
Number of words not been generated

### ISSUE THREAD

**Issue by HangryOpossum** [CollinBrennan/word-generator#6]
So when you have a complex filter or other restrictions it causes the generator to only try the number of times you have entered regardless of output, so one time I had to put in 10,000-5,000 words just for it to give me 500-250 words, so would it be possible to shift the index as it were or a counter to how many has been made, so if I ask for 200 words it adds to how many it has successfully made rather than how many tries it has done.

**Comment by CollinBrennan** [comment]
The way the filters currently work is to prevent infinite loops in the program since there is no guarantee that the number of words you ask for are possible to be generated from your ruleset.

For example, if I just put the character 'a' as my pattern and turned duplicates off, the program would go on forever trying to generate "successful" words.
